title: A test GitHub pages site
author: Tim Keighley
email: Tim.Keighley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning how to use GitHub pages.

# social links
# twitter_username: your-twitter-handle
github_username: TimKeighley

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
